/*
 * Оrganization: GosNIIAS
 * Year        : 2023
 * Author      : Vorobev Alexey Vitalievich
 * EMail       : vorobev_av@gosniias.ru
 */

#ifndef GIGEVISION_COMMANDS_H
#define GIGEVISION_COMMANDS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "GigEVision_Registers.h"

#define GIGEVISION_COMMAND_EXCLUSIVE_ACCESS_ON_ADDRESS  GIGEVISION_REGISTER_EXCLUSIVE_ACCESS
#define GIGEVISION_COMMAND_EXCLUSIVE_ACCESS_ON_VALUE    0x00000001
#define GIGEVISION_COMMAND_EXCLUSIVE_ACCESS_ON_TAG     "ExclusiveAccess_On"							/*Доступ включен*/

#define GIGEVISION_COMMAND_EXCLUSIVE_ACCESS_OFF_ADDRESS  GIGEVISION_REGISTER_EXCLUSIVE_ACCESS
#define GIGEVISION_COMMAND_EXCLUSIVE_ACCESS_OFF_VALUE    0x00000000
#define GIGEVISION_COMMAND_EXCLUSIVE_ACCESS_OFF_TAG     "ExclusiveAccess_Off"						/*Доступ отключен*/

#define GIGEVISION_COMMAND_HEARTBEAT_DISABLE_ON_ADDRESS  GIGEVISION_REGISTER_HEARTBEAT_DISABLE		
#define GIGEVISION_COMMAND_HEARTBEAT_DISABLE_ON_VALUE    0x00000000
#define GIGEVISION_COMMAND_HEARTBEAT_DISABLE_ON_TAG     "HeartbeatDisable_On"						/*Отключение сердцебиения включено*/

#define GIGEVISION_COMMAND_HEARTBEAT_DISABLE_OFF_ADDRESS  GIGEVISION_REGISTER_HEARTBEAT_DISABLE
#define GIGEVISION_COMMAND_HEARTBEAT_DISABLE_OFF_VALUE    0x00000001
#define GIGEVISION_COMMAND_HEARTBEAT_DISABLE_OFF_TAG     "HeartbeatDisable_Off"						/*Отключение сердцебиения*/

#define GIGEVISION_COMMAND_BALANCE_WHITE_AUTO_CONTINUOUS_ADDRESS  GIGEVISION_REGISTER_BALANCE_WHITE_AUTO
#define GIGEVISION_COMMAND_BALANCE_WHITE_AUTO_CONTINUOUS_VALUE    0x00000002
#define GIGEVISION_COMMAND_BALANCE_WHITE_AUTO_CONTINUOUS_TAG     "BalanceWhiteAuto_Continuous"		/*Баланс белого Автоматический непрерывный*/

#define GIGEVISION_COMMAND_ACQUISITION_MODE_CONTINUOUS_ADDRESS  GIGEVISION_REGISTER_ACQUISITION_MODE
#define GIGEVISION_COMMAND_ACQUISITION_MODE_CONTINUOUS_VALUE    0x00000001
#define GIGEVISION_COMMAND_ACQUISITION_MODE_CONTINUOUS_TAG     "AcquisitionMode_Continuous"			/*Режим сбора данных Непрерывный*/

#define GIGEVISION_COMMAND_ACQUISITION_MODE_SINGLE_FRAME_ADDRESS  GIGEVISION_REGISTER_ACQUISITION_MODE
#define GIGEVISION_COMMAND_ACQUISITION_MODE_SINGLE_FRAME_VALUE    0x00000002
#define GIGEVISION_COMMAND_ACQUISITION_MODE_SINGLE_FRAME_TAG     "AcquisitionMode_SingleFrame"		/*Однокадровый режим получения*/

#define GIGEVISION_COMMAND_ACQUISITION_ENABLE_ON_ADDRESS  GIGEVISION_REGISTER_ACQUISITION_ENABLE
#define GIGEVISION_COMMAND_ACQUISITION_ENABLE_ON_VALUE    0x00000001
#define GIGEVISION_COMMAND_ACQUISITION_ENABLE_ON_TAG     "AcquisitionEnable_On"						/*Включение сбора данных*/

#define GIGEVISION_COMMAND_ACQUISITION_ENABLE_OFF_ADDRESS  GIGEVISION_REGISTER_ACQUISITION_ENABLE
#define GIGEVISION_COMMAND_ACQUISITION_ENABLE_OFF_VALUE    0x00000000
#define GIGEVISION_COMMAND_ACQUISITION_ENABLE_OFF_TAG     "AcquisitionEnable_Off"					/*Выключение сбора данных*/

#define GIGEVISION_COMMAND_STREAM_DESTINATION_ADDRESS_ADDRESS  GIGEVISION_REGISTER_STREAM_DESTINATION_ADDRESS
#define GIGEVISION_COMMAND_STREAM_DESTINATION_ADDRESS_VALUE    0x00000000 /* Set by user */
#define GIGEVISION_COMMAND_STREAM_DESTINATION_ADDRESS_TAG     "StreamDestination_Address"			/*Адрес назначения потока*/

#define GIGEVISION_COMMAND_STREAM_DESTINATION_PORT_ADDRESS  GIGEVISION_REGISTER_STREAM_DESTINATION_PORT
#define GIGEVISION_COMMAND_STREAM_DESTINATION_PORT_VALUE    0x00000000 /* Set by user */
#define GIGEVISION_COMMAND_STREAM_DESTINATION_PORT_TAG     "StreamDestination_Port"					/*Порт назначения потока*/

#ifdef __cplusplus
}
#endif

#endif
